### ISSUE TITLE
sik skitaran strava

### ISSUE THREAD

**Issue by lapantiga** [trikaryateknologi/musclefitwebapp#1]
curl -X POST https://www.strava.com/oauth/token \
    -F client_id=17103 \
    -F client_secret=58781173f921c2759eb7c7b1a43ead4186e80ea5 \
    -F code=25c628ac52f2b075db44342fdfa9987eed30c56e

https://www.strava.com/oauth/authorize?client_id=17103&response_type=code&redirect_uri=http://103.252.101.105/token_exchange &scope=write&state=mystate&approval_prompt=force

![screen shot 2017-04-10 at 11 33 22 pm](https://cloud.githubusercontent.com/assets/10803190/24872054/2dfa1bb0-1e46-11e7-83ef-275091cbc2e1.png)

**Comment by manggala** [comment]
The strava authentication must be finalize. I have a mistake by making an assumption of `code` is the same as `access_token`

**Comment by lapantiga** [comment]
josss..gandoz...case closed....!!!
